name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm ci- -include=optional

      - name: Rebuild native modules
        run: npm rebuild

      - name: Move up Files 1
        run: cd ..

      - name: Move up Files 1
        run: cd ..

      - name: Check Files 1
        run: ls -al

      - name: Build Project
        run: npm run build

      - name: Check Files 2
        run: ls -al

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
